### ISSUE TITLE
Error reports in clojure buffers are upside down.

### ISSUE THREAD

**Issue by yehe01** [dnaumov/midje-mode#21]
![Screen Shot 2013-04-25 at 9 04 17](https://f.cloud.github.com/assets/1256556/425235/254ccaba-ada9-11e2-9eb6-74a09df80cf9.png)

As you can see from the image, midje-mode doesn't work well with nrepl. When i use midje-mode with nrepl 0.1.7 preview, it behaves unexpectedly (characters are not colorized properly). Now i upgrade nrepl to 0.1.8 preview. It's error reports in clojure buffers are upside down. Although it doesn't matter to some extent, but i still hope some one could have a look and fix.

**Comment by WhittlesJr** [comment]
This issue persists to this day. I would love to see this fixed. 

Really loving Midje though! 

;; CIDER 0.14.0 (Berlin), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.8.0_144
