### ISSUE TITLE
Error with flet

### ISSUE THREAD

**Issue by cch1** [dnaumov/midje-mode#36]
Working with the latest midje-mode (commit 816ba37cc8d281b8ca72b34980d815423e6cd4ff) I see this error message when opening `.clj` files in the test hierearchy:

`File mode specification error: (void-function flet)`

Emacs 24.4

**Comment by marick** [comment]
Try this commit: https://github.com/dnaumov/midje-mode/commit/6d04856d6e8cd8c394cd08849eeb2d636e4f15dd

I've tested it under 23.3, but it should work under 24.

**Comment by cch1** [comment]
Yep, that seems to fix the problem.

Thanks again, Brian.
