### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [dnaumov/midje-mode#41]
Could you please specify the license used by this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by marick** [comment]
Why is the `LICENSE` file not sufficient? https://github.com/marick/Midje/blob/master/LICENSE

Note also this at the home page:
<img width="409" alt="screen shot 2017-07-29 at 7 55 21 pm" src="https://user-images.githubusercontent.com/71909/28749757-d542052a-7497-11e7-87ae-814bfd09930b.png">

**Comment by tarsius** [comment]
> Why is the LICENSE file not sufficient? https://github.com/marick/Midje/blob/master/LICENSE

Because it is in a different repository. Without you saying so explicitly there is no way of knowing that you intend for this to be released under the same terms as the related clojure project.

Please also look at https://melpa.org/#/midje-mode and compare it to pages about other packages. Melpa cannot display a description because it extracts that from the library header, and in the case of this package that is empty except for the summary line.

You should also consider adding a header as described in https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html, followed by

```
;;; Commentary:

;; bla
;; bla

;;; Code:
```

**Comment by marick** [comment]
You're right.

I added a CC0 license. I hope that's sufficient. If not, send a pull request.

**Comment by marick** [comment]
Oops: I means GPL 3, not CC0

**Comment by tarsius** [comment]
Thanks!
